VOLPY_DATASETS   = '/media/bandy/nvme_data/voltage/volpy_data'
HPC2_DATASETS    = '/media/bandy/nvme_exceria/voltage/datasets/archon'
OUTPUT_BASE_PATH = '/media/bandy/nvme_exceria/voltage/output'
MODEL_FILE       = '/media/bandy/nvme_data/voltage/models/model20220620_patchnorm/model_e11_v0.0456.h5'
TRAIN_BASE_PATH  = '/media/bandy/nvme_exceria/voltage/train'
