name: voltage
dependencies:
  - python=3.8
  - numpy<1.24
  - tensorflow-gpu=2.4.1
  - cython
  - tifffile
  - scikit-image
  - scikit-learn
  - ipykernel
  - nbconvert
  - pandas
  - matplotlib
  - pip
  - pip:
    - elasticdeform
    - read-roi

